# Generated by Django 3.2.11 on 2022-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_norm', models.CharField(max_length=10)),
                ('tax_class', models.IntegerField()),
                ('yearly_tax', models.FloatField()),
            ],
        ),
    ]
